services:
  laravel:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: laravel-api
    image: laravel-api:latest
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=todoify_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue-frontend
    image: vue-frontend:latest
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoify_db
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: